const data = [
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-62-346x310.jpg",
    title: "All Natural Italian-Style Chicken Meatballs",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 20,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-60-346x310.jpg",
    title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 23,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-46.jpg",
    title: "Field Roast Chao Cheese Creamy Original",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 24,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-59.jpg",
    title: "Blue Diamond Almonds Lightly Salted",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 27,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-32-346x310.jpg",
    title: "Nestle Original Coffee-Mate Coffee Creamer",
    rating: 5,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 24,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-7.jpg",
    title: "USDA Choice Angus Beef Stew Meat",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 29,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-5.jpg",
    title: "Vital Farms Pasture-Raised Egg Bites Bacon & Cheddar",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 35,
  },
  {
    img: "https://klbtheme.com/bacola/wp-content/uploads/2021/04/product-image-3.jpg",
    title: "Werther’s Original Caramel Hard Candies",
    rating: 4,
    oldPrice: 9.35,
    newPrice: 7.25,
    discount: 19,
  },
];

export default data;
